name: CI

on:
    push:
        branches: [main]

jobs:
    format_check:
        uses: ./format-check.yml

    type_check:
        needs: format_check
        uses: ./type-check.yml

    deploy_staging:
        needs: type_check
        uses: ./deploy-staging.yml
        secrets: inherit

    deploy:
        needs: deploy_staging
        uses: ./deploy.yml
        secrets: inherit
