name: CI

on:
    push:
        branches: [main]

jobs:
    format_check:
        uses: ./.github/workflows/format-check.yml

    type_check:
        needs: format_check
        uses: ./.github/workflows/type-check.yml

    deploy_staging:
        needs: type_check
        uses: ./.github/workflows/deploy-staging.yml
        secrets: inherit

    deploy:
        needs: deploy_staging
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
